FROM nginx:latest

# Image Label 
LABEL Author="Prateek Kumaawat"
LABEL Orgnization="Highsky IT Solutions Pvt. Ltd."
LABEL Image="Web finox Template"

# copy src code in nginx image 
COPY src /usr/share/nginx/html

# EXPOSE PORT 
EXPOSE 80