services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  flask:
    build: .
    container_name: flask-api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DB: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass

volumes:
  mysql-data:
